using System;
using System.Collections.Generic;
using RestSharp;
using Dskow.Weather.Client;
using Dskow.Weather.Model;

namespace Dskow.Weather.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStationApi
    {
        /// <summary>
        /// Finds Stations When used without optional parameters, fetches list of available stations. Use with optional parameters below to filter results
        /// </summary>
        /// <param name="datasetid">Optional. Accepts a valid dataset id or a chain of dataset ids separated by ampersands. Stations returned will be supported by dataset(s) specified</param>
        /// <param name="locationid">Optional. Accepts a valid location id or a chain of location ids separated by ampersands. Stations returned will contain data for the location(s) specified</param>
        /// <param name="datacategoryid">Optional. Accepts a valid data category id or an array of data category ids. Stations returned will be associated with the data category(ies) specified</param>
        /// <param name="datatypeid">Optional. Accepts a valid data type id or a chain of data type ids separated by ampersands. Stations returned will contain all of the data type(s) specified</param>
        /// <param name="extent">Optional. The desired geographical extent for search. Designed to take a parameter generated by Google Maps API V3 LatLngBounds.toUrlValue. Stations returned must be located within the extent specified.</param>
        /// <param name="startdate">Optional. Accepts valid ISO formated date (yyyy-mm-dd). Stations returned will have data after the specified date. Paramater can be use independently of enddate</param>
        /// <param name="enddate">Optional. Accepts valid ISO formated date (yyyy-mm-dd). Stations returned will have data before the specified date. Paramater can be use independently of startdate</param>
        /// <param name="sortfield">Optional. The field to sort results by. Supports id, name, mindate, maxdate, and datacoverage fields</param>
        /// <param name="sortorder">Optional. Which order to sort by, asc or desc. Defaults to asc</param>
        /// <param name="limit">Optional. Defaults to 25, limits the number of results in the response. Maximum is 1000</param>
        /// <param name="offset">Optional. Defaults to 0, used to offset the resultlist. The example would begin with record 24</param>
        /// <returns>StationResult</returns>
        StationResult FindStations(List<string> datasetid, List<string> locationid, List<string> datacategoryid, List<string> datatypeid, List<string> extent, DateTime? startdate, DateTime? enddate, string sortfield, string sortorder, long? limit, long? offset);
        /// <summary>
        /// Find station by ID Returns a single station
        /// </summary>
        /// <param name="stationId">ID of station to return</param>
        /// <returns>StationResult</returns>
        StationResult GetStationById(long? stationId);
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class StationApi : IStationApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StationApi"/> class.
        /// </summary>
        /// <param name="apiClient"> an instance of ApiClient (optional)</param>
        /// <returns></returns>
        public StationApi(ApiClient apiClient = null)
        {
            if (apiClient == null) // use the default one in Configuration
                this.ApiClient = Configuration.DefaultApiClient;
            else
                this.ApiClient = apiClient;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StationApi(String basePath)
        {
            this.ApiClient = new ApiClient(basePath);
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <param name="basePath">The base path</param>
        /// <value>The base path</value>
        public void SetBasePath(String basePath)
        {
            this.ApiClient.BasePath = basePath;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <param name="basePath">The base path</param>
        /// <value>The base path</value>
        public String GetBasePath(String basePath)
        {
            return this.ApiClient.BasePath;
        }

        /// <summary>
        /// Gets or sets the API client.
        /// </summary>
        /// <value>An instance of the ApiClient</value>
        public ApiClient ApiClient { get; set; }

        /// <summary>
        /// Finds Stations When used without optional parameters, fetches list of available stations. Use with optional parameters below to filter results
        /// </summary>
        /// <param name="datasetid">Optional. Accepts a valid dataset id or a chain of dataset ids separated by ampersands. Stations returned will be supported by dataset(s) specified</param>
        /// <param name="locationid">Optional. Accepts a valid location id or a chain of location ids separated by ampersands. Stations returned will contain data for the location(s) specified</param>
        /// <param name="datacategoryid">Optional. Accepts a valid data category id or an array of data category ids. Stations returned will be associated with the data category(ies) specified</param>
        /// <param name="datatypeid">Optional. Accepts a valid data type id or a chain of data type ids separated by ampersands. Stations returned will contain all of the data type(s) specified</param>
        /// <param name="extent">Optional. The desired geographical extent for search. Designed to take a parameter generated by Google Maps API V3 LatLngBounds.toUrlValue. Stations returned must be located within the extent specified.</param>
        /// <param name="startdate">Optional. Accepts valid ISO formated date (yyyy-mm-dd). Stations returned will have data after the specified date. Paramater can be use independently of enddate</param>
        /// <param name="enddate">Optional. Accepts valid ISO formated date (yyyy-mm-dd). Stations returned will have data before the specified date. Paramater can be use independently of startdate</param>
        /// <param name="sortfield">Optional. The field to sort results by. Supports id, name, mindate, maxdate, and datacoverage fields</param>
        /// <param name="sortorder">Optional. Which order to sort by, asc or desc. Defaults to asc</param>
        /// <param name="limit">Optional. Defaults to 25, limits the number of results in the response. Maximum is 1000</param>
        /// <param name="offset">Optional. Defaults to 0, used to offset the resultlist. The example would begin with record 24</param>
        /// <returns>StationResult</returns>
        public StationResult FindStations(List<string> datasetid, List<string> locationid, List<string> datacategoryid, List<string> datatypeid, List<string> extent, DateTime? startdate, DateTime? enddate, string sortfield, string sortorder, long? limit, long? offset)
        {

            var path = "/stations";
            path = path.Replace("{format}", "json");

            var queryParams = new Dictionary<String, String>();
            var headerParams = new Dictionary<String, String>();
            var formParams = new Dictionary<String, String>();
            var fileParams = new Dictionary<String, FileParameter>();
            String postBody = null;

            if (datasetid != null) queryParams.Add("datasetid", ApiClient.ParameterToString(datasetid)); // query parameter
            if (locationid != null) queryParams.Add("locationid", ApiClient.ParameterToString(locationid)); // query parameter
            if (datacategoryid != null) queryParams.Add("datacategoryid", ApiClient.ParameterToString(datacategoryid)); // query parameter
            if (datatypeid != null) queryParams.Add("datatypeid", ApiClient.ParameterToString(datatypeid)); // query parameter
            if (extent != null) queryParams.Add("extent", ApiClient.ParameterToString(extent)); // query parameter
            if (startdate != null) queryParams.Add("startdate", ApiClient.ParameterToString(startdate?.ToString("yyyy-MM-ddThh:mm:ss"))); // query parameter
            if (enddate != null) queryParams.Add("enddate", ApiClient.ParameterToString(enddate?.ToString("yyyy-MM-ddThh:mm:ss"))); // query parameter
            if (sortfield != null) queryParams.Add("sortfield", ApiClient.ParameterToString(sortfield)); // query parameter
            if (sortorder != null) queryParams.Add("sortorder", ApiClient.ParameterToString(sortorder)); // query parameter
            if (limit != null) queryParams.Add("limit", ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) queryParams.Add("offset", ApiClient.ParameterToString(offset)); // query parameter

            // authentication setting, if any
            String[] authSettings = new String[] { };

            // make the HTTP request
            RestResponse response = (RestResponse)ApiClient.CallApi(path, Method.Get, queryParams, postBody, headerParams, formParams, fileParams, authSettings);
            
            if (((int)response.StatusCode) >= 400)
                throw new ApiException((int)response.StatusCode, "Error calling FindStations: " + response.Content, response.Content);
            else if (((int)response.StatusCode) == 0)
                throw new ApiException((int)response.StatusCode, "Error calling FindStations: " + response.ErrorMessage, response.ErrorMessage);

            return (StationResult)ApiClient.Deserialize(response.Content, typeof(StationResult), (IList<Parameter>)response.Headers);
        }

        /// <summary>
        /// Find station by ID Returns a single station
        /// </summary>
        /// <param name="stationId">ID of station to return</param>
        /// <returns>StationResult</returns>
        public StationResult GetStationById(long? stationId)
        {
            // verify the required parameter 'stationId' is set
            if (stationId == null) throw new ApiException(400, "Missing required parameter 'stationId' when calling GetStationById");

            var path = "/stations/{stationId}";
            path = path.Replace("{format}", "json");
            path = path.Replace("{" + "stationId" + "}", ApiClient.ParameterToString(stationId));

            var queryParams = new Dictionary<String, String>();
            var headerParams = new Dictionary<String, String>();
            var formParams = new Dictionary<String, String>();
            var fileParams = new Dictionary<String, FileParameter>();
            String postBody = null;


            // authentication setting, if any
            String[] authSettings = new String[] { "api_key" };

            // make the HTTP request
            RestResponse response = (RestResponse)ApiClient.CallApi(path, Method.Get, queryParams, postBody, headerParams, formParams, fileParams, authSettings);

            if (((int)response.StatusCode) >= 400)
                throw new ApiException((int)response.StatusCode, "Error calling GetStationById: " + response.Content, response.Content);
            else if (((int)response.StatusCode) == 0)
                throw new ApiException((int)response.StatusCode, "Error calling GetStationById: " + response.ErrorMessage, response.ErrorMessage);

            return (StationResult)ApiClient.Deserialize(response.Content, typeof(StationResult), (IList<Parameter>)response.Headers);
        }

    }
}
